import { GoHomeFill } from "react-icons/go";

const drugs = [
  ,
  //   expiryDate: "2024-12-31",
  // },
  {
    id: 1,
    qty: 3,
    quantity: 3,
    name: "Aspirin",
    category: "Analgesic",
    type: "Tablet",
    supp: "wisesdf",
    sellingPrice: 23,
    costPrice: 12,
    expiryDate: "2024-12-31",
  },
  {
    id: 2,
    qty: 9,
    quantity: 9,
    name: "Paracetamol",
    category: "Analgesic",
    type: "Tablet",
    supp: "wisesdf",
    sellingPrice: 23,
    costPrice: 12,
    expiryDate: "2024-12-31",
  },
  {
    id: 3,
    qty: 5,
    quantity: 5,
    name: "Ibuprofen",
    category: "NSAID",
    type: "Tablet",
    supp: "wisesdf",
    sellingPrice: 23,
    costPrice: 12,
    expiryDate: "2024-12-31",
  },
  {
    id: 4,
    qty: 34,
    quantity: 34,
    name: "Amoxicillin",
    category: "Antibiotic",
    type: "Capsule",
    supp: "wisesdf",
    sellingPrice: 23,
    costPrice: 12,
    expiryDate: "2024-12-31",
  },
  {
    id: 5,
    qty: 3,
    quantity: 3,
    name: "Omeprazole",
    category: "Proton Pump Inhibitor",
    type: "Capsule",
    supp: "wisesdf",
    sellingPrice: 23,
    costPrice: 12,
    expiryDate: "2024-12-31",
  },
  {
    id: 6,
    qty: 34,
    quantity: 34,
    name: "Loratadine",
    category: "Antihistamine",
    type: "Tablet",
    supp: "wisesdf",
    sellingPrice: 23,
    costPrice: 12,
    expiryDate: "2024-12-31",
  },
  {
    id: 7,
    qty: 0,
    quantity: 0,
    name: "Morphine",
    category: "Opioid",
    type: "Tablet",
    supp: "wisesdf",
    sellingPrice: 23,
    costPrice: 12,
    expiryDate: "2024-12-31",
  },
  {
    id: 8,
    qty: 34,
    quantity: 34,
    name: "Diazepam",
    category: "Benzodiazepine",
    type: "Tablet",
    supp: "wisesdf",
    sellingPrice: 23,
    costPrice: 12,
    expiryDate: "2024-12-31",
  },
  {
    id: 9,
    qty: 3,
    quantity: 3,
    name: "Dexamethasone",
    category: "CorticostPriceeroid",
    type: "Tablet",
    supp: "wisesdf",
    sellingPrice: 23,
    costPrice: 12,
    expiryDate: "2024-12-31",
  },
  {
    id: 10,
    qty: 2,
    quantity: 2,
    name: "Codeine",
    category: "Opioid",
    type: "Syrup",
    supp: "wisesdf",
    sellingPrice: 23,
    costPrice: 12,
    expiryDate: "2024-12-31",
  },
];

const navigations = [
  {
    name: "Sales",
    link: "/pos",
    icon: <GoHomeFill />,
  },
  {
    name: "Stocks",
    link: "/stocks",
    icon: <GoHomeFill />,
  },
];

export { drugs, navigations };
