const drugs = [
  {
    id: 1,
    qty:3,
    name: "Aspirin",
    category: "Analgesic",
    type: "Tablet",
    price: 23,
    cost: 12,
  },
  {
    id: 2,
    qty:9,
    name: "Paracetamol",
    category: "Analgesic",
    type: "Tablet",
    price: 23,
    cost: 12,
  },
  {
    id: 3,
    qty:5,
    name: "Ibuprofen",
    category: "NSAID",
    type: "Tablet",
    price: 23,
    cost: 12,
  },
  {
    id: 4,
    qty:34,
    name: "Amoxicillin",
    category: "Antibiotic",
    type: "Capsule",
    price: 23,
    cost: 12,
  },
  {
    id: 5,
    qty:3,
    name: "Omeprazole",
    category: "Proton Pump Inhibitor",
    type: "Capsule",
    price: 23,
    cost: 12,
  },
  {
    id: 6,
    qty:34,
    name: "Loratadine",
    category: "Antihistamine",
    type: "Tablet",
    price: 23,
    cost: 12,
  },
  {
    id: 7,
    qty:0,
    name: "Morphine",
    category: "Opioid",
    type: "Tablet",
    price: 23,
    cost: 12,
  },
  {
    id: 8,
    qty:34,
    name: "Diazepam",
    category: "Benzodiazepine",
    type: "Tablet",
    price: 23,
    cost: 12,
  },
  {
    id: 9,
    qty:3,
    name: "Dexamethasone",
    category: "Corticosteroid",
    type: "Tablet",
    price: 23,
    cost: 12,
  },
  {
    id: 10,
    qty:2,
    name: "Codeine",
    category: "Opioid",
    type: "Syrup",
    price: 23,
    cost: 12,
  },
];

export { drugs };
